#define KERNEL_DIM 3 
#define SIMD1 2 
#define PE1 1 
#define MMV1 2 
#define WIDTH 1 
#define IFM_Channels1 2 
#define OFM_Channels1 1 
#define IFMDim1 8 
#define OFMDim1 6 
#define STRIDE 1 
#define INPUT_PRECISION 8 
#define TILE1 9 
#define ACTIVATION_PRECISION 16 
